services:
  # PostgreSQL Database for Airflow
  - type: pserv
    name: airflow-postgres
    plan: free
    env: docker
    envVars:
      - key: POSTGRES_USER
        value: airflow
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_DB
        value: airflow

  # Airflow Webserver - The main web interface
  - type: web
    name: airflow-webserver
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: airflow webserver
    envVars:
      - key: AIRFLOW__CORE__EXECUTOR
        value: LocalExecutor
      - key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
        fromService:
          type: pserv
          name: airflow-postgres
          envVarKey: INTERNAL_DATABASE_URL
          format: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@${host}:${port}/airflow
      - key: AIRFLOW__WEBSERVER__SECRET_KEY
        generateValue: true
      - key: AIRFLOW_UID
        value: "50000"
      - key: TMDB_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    healthCheckPath: /health

  # Airflow Init Job - Runs once to initialize the database (using web service type instead of cron)
  - type: web
    name: airflow-init
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: >
      bash -c "
      airflow db migrate &&
      airflow users create
        --username admin
        --password ${ADMIN_PASSWORD}
        --firstname Anonymous
        --lastname User
        --role Admin
        --email admin@example.com &&
      airflow connections add
        --conn-id tmdb_default
        --conn-type http
        --conn-password ${TMDB_API_KEY} &&
      airflow connections add
        --conn-id supabase_default
        --conn-type generic
        --conn-host ${SUPABASE_URL}
        --conn-password ${SUPABASE_KEY} &&
      echo 'Initialization complete. You can now shut down this service.' &&
      sleep infinity
      "
    envVars:
      - key: AIRFLOW__CORE__EXECUTOR
        value: LocalExecutor
      - key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
        fromService:
          type: pserv
          name: airflow-postgres
          envVarKey: INTERNAL_DATABASE_URL
          format: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@${host}:${port}/airflow
      - key: AIRFLOW_UID
        value: "50000"
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: TMDB_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false