databases:
  - name: airflow-postgres
    databaseName: airflow
    user: airflow
    plan: free

services:
  # Web UI - Chỉ giữ lại service web UI vì đây là dịch vụ quan trọng nhất
  - type: web
    name: airflow-webserver
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    preDeployCommand: airflow db init && airflow users create --username $AIRFLOW_ADMIN_USERNAME --password $AIRFLOW_ADMIN_PASSWORD --firstname Admin --lastname User --role Admin --email $AIRFLOW_ADMIN_EMAIL
    startCommand: airflow webserver
    envVars:
      - key: AIRFLOW__CORE__EXECUTOR
        value: LocalExecutor
      - key: AIRFLOW__WEBSERVER__SECRET_KEY
        generateValue: true
      - key: AIRFLOW_ADMIN_USERNAME
        value: admin
      - key: AIRFLOW_ADMIN_PASSWORD
        generateValue: true
      - key: AIRFLOW_ADMIN_EMAIL
        value: admin@example.com
      - key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-postgres
          property: connectionString
    domains:
      - airflow.onrender.com 